baseURL = 'https://nikolabs.ai/'
languageCode = 'en-us'
title = 'Nikolabs'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term', 'RSS', 'sitemap']

[params]
description = 'We build apps.'
noindex = true

[menu]
  [[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

  # Stealth mode: keep navigation minimal

  # About page exists but is hidden from the main menu in stealth mode

  [[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10
