baseURL = 'https://nikolabs.ai/'
languageCode = 'en-us'
title = 'Nikolabs'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
description = 'Nikolabs designs, builds, and launches its own mobile, web, and AI-powered apps.'

[menu]
  [[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = 1

  [[menu.main]]
  identifier = 'apps'
  name = 'Apps'
  url = '/apps/'
  weight = 2

  [[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = 3

  [[menu.main]]
  identifier = 'contact'
  name = 'Contact'
  url = '/contact/'
  weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
  pagerSize = 10
